import OpenAI from 'openai';
import { promises as fs, createReadStream } from 'fs';
import path from 'path';
import https from 'https';
import http from 'http';
import { v4 as uuidv4 } from 'uuid';
import { getScreenshotById } from './database';
import { getGeneratedImagesDir, getGeneratedImagePath, getGeneratedImageUrl, ensureDir } from './filePaths';

// Note: dotenv is loaded in index.ts
// This service relies on process.env being set by index.ts

// Initialize OpenAI client
const getOpenAIClient = (): OpenAI => {
  const apiKey = process.env.OPENAI_API_KEY;
  
  if (!apiKey) {
    console.error('❌ OPENAI_API_KEY não encontrada.');
    console.error('📁 __dirname atual:', __dirname);
    console.error('📁 process.cwd():', process.cwd());
    
    // Show all environment variables that contain OPENAI
    const openaiVars = Object.keys(process.env).filter(k => k.toUpperCase().includes('OPENAI'));
    if (openaiVars.length > 0) {
      console.error('🔍 Variáveis de ambiente encontradas com "OPENAI":', openaiVars);
      openaiVars.forEach(key => {
        const value = process.env[key];
        const maskedValue = value ? `${value.substring(0, 10)}...` : '(vazio)';
        console.error(`   ${key} = ${maskedValue}`);
      });
    } else {
      console.error('🔍 Nenhuma variável de ambiente contendo "OPENAI" foi encontrada.');
    }
    
    // Show all env vars (for debugging - remove in production)
    console.error('📋 Todas as variáveis de ambiente:', Object.keys(process.env).sort().join(', '));
    
    console.error('💡 Dica: Certifique-se de que o arquivo .env está na raiz do backend com OPENAI_API_KEY=seu_token_aqui');
    console.error('💡 Certifique-se também de que não há espaços ao redor do = no arquivo .env');
    throw new Error('OPENAI_API_KEY não configurada. Configure a variável de ambiente OPENAI_API_KEY.');
  }
  
  console.log('✅ OPENAI_API_KEY encontrada e configurada.');
  return new OpenAI({
    apiKey: apiKey
  });
};

/**
 * Analyze a screenshot image using OpenAI Vision API
 * @param imagePath - Path to the image file
 * @param prompt - User prompt/question about the image
 * @returns Response from OpenAI
 */
export async function analyzeScreenshot(
  imagePath: string,
  prompt: string
): Promise<string> {
  try {
    // Check if image file exists
    try {
      await fs.access(imagePath);
    } catch {
      throw new Error(`Arquivo de imagem não encontrado: ${imagePath}`);
    }

    // Read image file and convert to base64
    const imageBuffer = await fs.readFile(imagePath);
    const base64Image = imageBuffer.toString('base64');
    
    // Get file extension to determine MIME type
    const ext = path.extname(imagePath).toLowerCase();
    let mimeType = 'image/png';
    if (ext === '.jpg' || ext === '.jpeg') {
      mimeType = 'image/jpeg';
    } else if (ext === '.png') {
      mimeType = 'image/png';
    } else if (ext === '.webp') {
      mimeType = 'image/webp';
    }

    const openai = getOpenAIClient();

    // Call OpenAI Vision API
    const response = await openai.chat.completions.create({
      model: 'gpt-4o', // Using GPT-4o which supports vision
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: prompt
            },
            {
              type: 'image_url',
              image_url: {
                url: `data:${mimeType};base64,${base64Image}`
              }
            }
          ]
        }
      ],
      max_tokens: 1000
    });

    const content = response.choices[0]?.message?.content;
    
    if (!content) {
      throw new Error('Resposta vazia da OpenAI');
    }

    return content;
  } catch (error: any) {
    // Handle OpenAI API errors
    if (error.status) {
      const errorMessage = error.message || 'Erro desconhecido da API OpenAI';
      throw new Error(`Erro da API OpenAI (${error.status}): ${errorMessage}`);
    }
    // Handle other errors
    const errorMessage = error.message || String(error);
    throw new Error(`Erro ao analisar screenshot: ${errorMessage}`);
  }
}

/**
 * Generate HTML from a screenshot image using OpenAI Vision API
 * @param imagePath - Path to the image file
 * @returns HTML content generated by OpenAI
 */
export async function generateHTMLFromScreenshot(
  imagePath: string
): Promise<string> {
  const prompt = `Analise esta imagem cuidadosamente e gere um código HTML5 completo, bem estruturado e responsivo que tenha o MESMO OBJETIVO e conteúdo da imagem, mas adaptado para web.

IMPORTANTE SOBRE A GERAÇÃO:
- A página HTML NÃO precisa ser uma cópia visual idêntica do screenshot
- O objetivo é criar uma página web funcional que tenha o MESMO PROPÓSITO e conteúdo da imagem
- Você pode adaptar o design para ser mais moderno, adequado para web e melhorar a experiência do usuário
- Foque em preservar o CONTEÚDO, FUNCIONALIDADE e OBJETIVO, não necessariamente a aparência exata
- Seja criativo na adaptação visual, mantendo a essência e propósito do conteúdo original
- Priorize usabilidade web e design moderno sobre fidelidade visual absoluta

REQUISITOS OBRIGATÓRIOS:
- Estrutura HTML5 completa com <!DOCTYPE html>, <html>, <head> e <body>
- Estilos CSS em uma tag <style> dentro do <head> (evite estilos inline quando possível)
- NÃO use tags semânticas de estrutura como <header>, <nav>, <footer>, <main>
- Use apenas elementos de conteúdo: <div>, <section>, <article>, <table>, <ul>, <ol>, <p>, <h1>-<h6>, etc.
- O conteúdo deve estar diretamente no <body>, sem wrappers de estrutura como <header>
- Layout responsivo usando CSS moderno (flexbox ou grid quando apropriado)
- Cores, fontes e espaçamentos podem ser adaptados para um design web moderno (não precisa ser idêntico à imagem)
- Se houver texto na imagem, preserve o CONTEÚDO e SIGNIFICADO, mas pode adaptar a formatação para melhor legibilidade web
- Mantenha a hierarquia e organização do conteúdo, mas pode melhorar a apresentação visual
- Se houver tabelas, recrie-as com <table>, <thead>, <tbody>, <tr>, <td>, <th>
- Se houver listas, use <ul> ou <ol> com <li>
- Se houver títulos ou cabeçalhos, use <h1> a <h6> apropriadamente (mas NÃO dentro de tags <header>)
- Preserve a hierarquia e estrutura lógica do conteúdo (não precisa ser visualmente idêntica)
- Adapte o layout para ser mais adequado para web, mantendo o mesmo propósito e funcionalidade

CAMPOS DE INPUT E FORMULÁRIOS (CRÍTICO):
- Se houver campos de texto, caixas de entrada, áreas de texto ou campos de formulário na imagem:
  * Identifique TODOS os campos de input visíveis (campos de texto, textarea, select, checkbox, radio buttons, etc.)
  * Crie elementos HTML interativos correspondentes usando <input>, <textarea>, <select>, <button>, etc.
  * Para campos de texto: use <input type="text"> ou <input type="email">, <input type="number"> conforme apropriado
  * Para áreas de texto maiores: use <textarea>
  * Para seleções: use <select> com <option>
  * Para checkboxes: use <input type="checkbox">
  * Para radio buttons: use <input type="radio">
  * Para botões: use <button type="button"> ou <input type="submit">
- Preserve labels e textos associados aos campos usando <label> ou placeholders
- Se houver texto placeholder ou dicas visíveis nos campos, inclua-os como atributo placeholder="..."
- Se houver valores pré-preenchidos visíveis, inclua-os como atributo value="..."
- Mantenha a funcionalidade e propósito dos campos (pode adaptar o layout para melhor usabilidade web)
- Agrupe campos relacionados em <form> ou <fieldset> quando apropriado
- Use atributos name e id apropriados para cada campo
- Garanta que os campos sejam totalmente funcionais e interativos

DIRETRIZES DE DESIGN - LAYOUT MODERNO E ELEGANTE:
- Use um design limpo, moderno e profissional
- Cor de fundo: use cores claras e suaves (#ffffff, #f8f9fa, #fafbfc ou similares) para melhor legibilidade
- Cor de texto: use cores escuras (#1a1a1a, #2d2d2d, #333333) para contraste adequado
- Tipografia: use fontes modernas e legíveis, com hierarquia clara (tamanhos diferentes para títulos e parágrafos)
- Espaçamento: use padding e margin generosos para criar respiração visual (mínimo 1rem entre elementos)
- Tabelas: design limpo com bordas sutis, linhas alternadas para melhor leitura, e cores suaves
- Links: use cores vibrantes mas profissionais (#9c27b0, #1976d2 ou similares) com hover suave
- Campos de input: design moderno com bordas arredondadas, sombras sutis, e estados de foco bem definidos
- Botões: design moderno com bordas arredondadas, gradientes suaves ou cores sólidas vibrantes, e efeitos hover elegantes
- Sombras: use sombras sutis e suaves para dar profundidade sem exagerar
- Bordas: use bordas arredondadas (border-radius) para um visual mais moderno
- Use unidades relativas (rem, em, %) para melhor responsividade
- Garanta que o conteúdo seja legível e visualmente atraente em diferentes tamanhos de tela
- Mantenha proporções e espaçamentos similares à imagem original, mas com melhorias visuais
- Estilize campos de input com aparência moderna: bordas arredondadas, padding adequado, cores suaves
- Campos de input devem ter estados hover e focus bem definidos com transições suaves

IMAGENS E ILUSTRAÇÕES:
- Se a imagem contiver ilustrações, gráficos, diagramas, ícones decorativos ou imagens que não sejam fotografias de texto/tabelas:
  * Use placeholders especiais no formato: <img src="GENERATE_IMAGE:descrição detalhada da imagem" alt="descrição" />
  * A descrição deve ser detalhada e específica sobre o que a imagem deve mostrar
  * Exemplo: <img src="GENERATE_IMAGE:um ícone de lâmpada amarela brilhante com raios de luz ao redor" alt="ícone de ideia" />
  * Use este formato APENAS para imagens que precisam ser geradas, não para texto ou tabelas
  * Para conteúdo textual ou tabular, use HTML puro sem imagens

IMPORTANTE:
- Retorne APENAS o código HTML completo, sem explicações, comentários ou markdown
- O código deve ser válido e pronto para renderização imediata em um navegador
- Não inclua tags <script> ou JavaScript
- Foque em criar uma página web funcional com o MESMO OBJETIVO e conteúdo da imagem, adaptada para web
- PRIORIDADE MÁXIMA: Se houver campos de input na imagem, eles DEVEM ser incluídos como elementos HTML interativos funcionais
- Lembre-se: você está criando uma página WEB, não uma cópia pixel-perfect da imagem - adapte para melhor experiência web

NÃO INCLUIR:
- NÃO adicione elementos de paginação (números de página, "Página X de Y", rodapés com paginação, etc.)
- NÃO inclua controles de navegação entre páginas
- NÃO adicione elementos que não estejam visíveis na imagem original
- NÃO use tags <header>, <nav>, <footer> ou outras tags de estrutura semântica
- Foque apenas no conteúdo visual presente na imagem, sem adicionar elementos de interface de paginação ou estrutura
- O HTML deve conter APENAS o conteúdo para exibição, sem wrappers estruturais desnecessários`;

  try {
    // Check if image file exists
    try {
      await fs.access(imagePath);
    } catch {
      throw new Error(`Arquivo de imagem não encontrado: ${imagePath}`);
    }

    // Read image file and convert to base64
    const imageBuffer = await fs.readFile(imagePath);
    const base64Image = imageBuffer.toString('base64');
    
    // Get file extension to determine MIME type
    const ext = path.extname(imagePath).toLowerCase();
    let mimeType = 'image/png';
    if (ext === '.jpg' || ext === '.jpeg') {
      mimeType = 'image/jpeg';
    } else if (ext === '.png') {
      mimeType = 'image/png';
    } else if (ext === '.webp') {
      mimeType = 'image/webp';
    }

    const openai = getOpenAIClient();

    // Call OpenAI Vision API
    const response = await openai.chat.completions.create({
      model: 'gpt-4o', // Using GPT-4o which supports vision
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: prompt
            },
            {
              type: 'image_url',
              image_url: {
                url: `data:${mimeType};base64,${base64Image}`
              }
            }
          ]
        }
      ],
      max_tokens: 4000 // Increased for HTML generation
    });

    const content = response.choices[0]?.message?.content;
    
    if (!content) {
      throw new Error('Resposta vazia da OpenAI');
    }

    // Clean up the response - remove markdown code blocks if present
    let htmlContent = content.trim();
    if (htmlContent.startsWith('```html')) {
      htmlContent = htmlContent.replace(/^```html\n?/, '').replace(/\n?```$/, '');
    } else if (htmlContent.startsWith('```')) {
      htmlContent = htmlContent.replace(/^```\n?/, '').replace(/\n?```$/, '');
    }

    // Remove tags <header> e </header> caso ainda existam (extração do conteúdo)
    htmlContent = htmlContent.replace(/<header[^>]*>[\s\S]*?<\/header>/gi, (match) => {
      // Extrai apenas o conteúdo interno do header, removendo a tag
      return match.replace(/<header[^>]*>/gi, '').replace(/<\/header>/gi, '');
    });

    // Basic validation: check if HTML structure exists
    const hasHTMLStructure = /<html[\s>]|<body[\s>]|<div[\s>]|<section[\s>]|<main[\s>]/i.test(htmlContent);
    if (!hasHTMLStructure && htmlContent.length > 0) {
      // If no HTML structure found, wrap content in basic HTML structure (sem header)
      htmlContent = `<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Conteúdo Gerado</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      margin: 0;
      padding: 20px;
      max-width: 1200px;
      margin: 0 auto;
      background-color: #ffffff;
      color: #2d2d2d;
    }
  </style>
</head>
<body>
${htmlContent}
</body>
</html>`;
    }

    // Validate minimum length
    if (htmlContent.length < 50) {
      throw new Error('HTML gerado é muito curto ou inválido');
    }

    return htmlContent;
  } catch (error: any) {
    // Handle OpenAI API errors
    if (error.status) {
      const errorMessage = error.message || 'Erro desconhecido da API OpenAI';
      throw new Error(`Erro da API OpenAI (${error.status}): ${errorMessage}`);
    }
    // Handle other errors
    const errorMessage = error.message || String(error);
    throw new Error(`Erro ao gerar HTML: ${errorMessage}`);
  }
}

/**
 * Convert seconds to LRC timestamp format [mm:ss.xx]
 */
function secondsToLRCTimestamp(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  const centiseconds = Math.floor((seconds % 1) * 100);
  return `[${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(centiseconds).padStart(2, '0')}]`;
}

/**
 * Generate LRC data from Whisper API response
 */
/**
 * Group words into paragraphs based on sentence endings
 * Groups 2-3 sentences per paragraph for better readability
 */
function groupWordsIntoParagraphs(words: Array<{ word: string; start: number; end: number }>): Array<{ text: string; timestamp: number }> {
  const paragraphs: Array<{ text: string; timestamp: number }> = [];
  let currentParagraph: { words: string[]; timestamp: number; sentenceCount: number } | null = null;

  for (let i = 0; i < words.length; i++) {
    const wordData = words[i];
    let word = wordData.word.trim();
    if (word.length === 0) continue;

    // Check if word ends a sentence (look for punctuation at the end)
    const endsSentence = /[.!?]+$/.test(word);

    if (!currentParagraph) {
      // Start new paragraph
      currentParagraph = {
        words: [word],
        timestamp: wordData.start,
        sentenceCount: endsSentence ? 1 : 0
      };
    } else {
      // Add space before word if needed
      const lastWord = currentParagraph.words[currentParagraph.words.length - 1];
      const needsSpace = !lastWord.endsWith(' ') && 
                        !word.startsWith(' ') && 
                        !lastWord.match(/[.!?]+$/) && 
                        !word.match(/^[.!?,:;]/);
      
      currentParagraph.words.push(needsSpace ? ' ' + word : word);
      
      // Increment sentence count when we encounter sentence-ending punctuation
      if (endsSentence) {
        currentParagraph.sentenceCount++;
      }
    }

    // Create paragraph every 2-3 sentences
    // Break after 2 sentences, or if we have 3+ sentences and hit another sentence end
    const shouldBreak = endsSentence && (
      currentParagraph.sentenceCount >= 3 || // Always break at 3+ sentences
      (currentParagraph.sentenceCount >= 2 && currentParagraph.sentenceCount % 2 === 0) || // Break at even sentence counts (2, 4, 6...)
      (i === words.length - 1) // Last word
    );

    if (shouldBreak) {
      const paragraphText = currentParagraph.words.join('').trim();
      if (paragraphText.length > 0) {
        paragraphs.push({
          text: paragraphText,
          timestamp: currentParagraph.timestamp
        });
        currentParagraph = null;
      }
    }
  }

  // Add remaining paragraph if exists (shouldn't happen with new logic, but safety check)
  if (currentParagraph) {
    const paragraphText = currentParagraph.words.join('').trim();
    if (paragraphText.length > 0) {
      paragraphs.push({
        text: paragraphText,
        timestamp: currentParagraph.timestamp
      });
    }
  }

  // Ensure we have at least one paragraph
  if (paragraphs.length === 0 && words.length > 0) {
    // Fallback: create one paragraph with all words
    const allText = words.map(w => w.word).join(' ').trim();
    paragraphs.push({
      text: allText,
      timestamp: words[0].start
    });
  }

  return paragraphs;
}

async function generateLRCFromWhisper(
  audioBuffer: Buffer,
  tempDir: string
): Promise<string> {
  const openai = getOpenAIClient();
  
  // Create temporary file for Whisper API
  const tempAudioPath = path.join(tempDir, `temp-audio-${uuidv4()}.mp3`);
  
  try {
    // Save audio buffer to temporary file
    await fs.writeFile(tempAudioPath, audioBuffer);
    
    // Create read stream for OpenAI API
    const audioStream = createReadStream(tempAudioPath);
    
    // Call Whisper API with word-level timestamps
    const transcription = await openai.audio.transcriptions.create({
      file: audioStream,
      model: 'whisper-1',
      response_format: 'verbose_json',
      timestamp_granularities: ['word']
    });
    
    // Process Whisper response and generate LRC paragraph by paragraph
    const lrcLines: string[] = [];
    
    // Type assertion for verbose_json response with word-level timestamps
    const verboseResponse = transcription as any;
    
    // Collect all words with timestamps
    const allWords: Array<{ word: string; start: number; end: number }> = [];
    
    // Whisper API returns segments, each with optional words array
    if (verboseResponse.segments && Array.isArray(verboseResponse.segments)) {
      // Process each segment
      for (const segment of verboseResponse.segments as any[]) {
        // If segment has words array, collect word-level timestamps
        if (segment.words && Array.isArray(segment.words)) {
          for (const word of segment.words) {
            allWords.push({
              word: word.word,
              start: word.start,
              end: word.end || word.start + 0.5 // Fallback if end not available
            });
          }
        } else if (segment.text) {
          // Fallback: treat segment as single word
          allWords.push({
            word: segment.text.trim(),
            start: segment.start,
            end: segment.end || segment.start + 1
          });
        }
      }
    } else if (verboseResponse.text) {
      // Last resort: use full text with estimated timestamp
      lrcLines.push(`[00:00.00]${verboseResponse.text}`);
      return lrcLines.join('\n');
    }

    // Group words into paragraphs
    if (allWords.length > 0) {
      console.log(`📝 Total de palavras coletadas: ${allWords.length}`);
      const paragraphs = groupWordsIntoParagraphs(allWords);
      console.log(`📄 Parágrafos criados: ${paragraphs.length}`);
      
      // Generate LRC lines (one per paragraph)
      for (const paragraph of paragraphs) {
        const timestamp = secondsToLRCTimestamp(paragraph.timestamp);
        lrcLines.push(`${timestamp}${paragraph.text}`);
        console.log(`✅ Parágrafo: [${timestamp}] ${paragraph.text.substring(0, 50)}...`);
      }
    } else {
      console.warn('⚠️ Nenhuma palavra coletada do Whisper, usando fallback');
    }
    
    // If no paragraphs were created, fallback to full text
    if (lrcLines.length === 0 && verboseResponse.text) {
      console.warn('⚠️ Nenhum parágrafo criado, usando texto completo como fallback');
      lrcLines.push(`[00:00.00]${verboseResponse.text}`);
    }
    
    return lrcLines.join('\n');
  } finally {
    // Clean up temporary file
    try {
      await fs.unlink(tempAudioPath);
    } catch (error) {
      console.warn('Erro ao remover arquivo temporário:', error);
    }
  }
}

/**
 * Generate audio explanation from a screenshot image using OpenAI
 * First analyzes the image to generate explanatory text, then converts to audio
 * Uses Whisper API to generate precise LRC timestamps
 * @param imagePath - Path to the image file
 * @returns Object containing the audio buffer, subtitle text, and LRC data
 */
export async function generateAudioExplanation(
  imagePath: string
): Promise<{ audioBuffer: Buffer; subtitleText: string; lrcData: string }> {
  try {
    // Check if image file exists
    try {
      await fs.access(imagePath);
    } catch {
      throw new Error(`Arquivo de imagem não encontrado: ${imagePath}`);
    }

    const openai = getOpenAIClient();

    // Step 1: Analyze the image and generate explanatory text
    const imageBuffer = await fs.readFile(imagePath);
    const base64Image = imageBuffer.toString('base64');
    
    const ext = path.extname(imagePath).toLowerCase();
    let mimeType = 'image/png';
    if (ext === '.jpg' || ext === '.jpeg') {
      mimeType = 'image/jpeg';
    } else if (ext === '.png') {
      mimeType = 'image/png';
    } else if (ext === '.webp') {
      mimeType = 'image/webp';
    }

    const explanationPromptEN = `You are an experienced and didactic teacher. Analyze this image and create a clear, educational, and engaging explanation about the content presented.
The explanation should:
- Be suitable for students
- Be clear and didactic, as if you were giving a class
- Explain the main concepts in an accessible way
- Have a friendly and professional tone
- Be approximately 1-2 minutes long when converted to audio
- Be written in a natural way, as if you were speaking directly to the students

Write the explanation as if you were speaking, not as a formal text. Use conversational and didactic language.`;

    // Generate explanatory text in English only
    const textResponseEN = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: 'You are an experienced, didactic, and friendly teacher who explains content in a clear and engaging way.'
        },
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: explanationPromptEN
            },
            {
              type: 'image_url',
              image_url: {
                url: `data:${mimeType};base64,${base64Image}`
              }
            }
          ]
        }
      ],
      max_tokens: 800
    });

    const explanationTextEN = textResponseEN.choices[0]?.message?.content;
    
    if (!explanationTextEN) {
      throw new Error('Não foi possível gerar a explicação em inglês');
    }

    // Step 2: Convert English text to speech using TTS API
    const audioResponse = await openai.audio.speech.create({
      model: 'tts-1',
      voice: 'nova', // Female voice that sounds like a teacher
      input: explanationTextEN,
      response_format: 'mp3'
    });

    // Convert the response to buffer
    const audioBuffer = Buffer.from(await audioResponse.arrayBuffer());

    // Step 3: Generate LRC using Whisper API
    let lrcData = '';
    try {
      // Create temporary directory for audio file
      const tempDir = path.join(__dirname, '../../temp');
      await ensureDir(tempDir);
      
      // Generate LRC from Whisper API
      lrcData = await generateLRCFromWhisper(audioBuffer, tempDir);
    } catch (whisperError: any) {
      console.warn('Erro ao gerar LRC com Whisper, usando fallback:', whisperError.message);
      // Fallback: create simple LRC with estimated timestamps
      // Estimate ~150 words per minute = 2.5 words per second
      const words = explanationTextEN.split(/\s+/);
      const estimatedDuration = words.length / 2.5; // seconds
      const timePerWord = estimatedDuration / words.length;
      
      const lrcLines: string[] = [];
      let currentTime = 0;
      for (const word of words) {
        const timestamp = secondsToLRCTimestamp(currentTime);
        lrcLines.push(`${timestamp}${word}`);
        currentTime += timePerWord;
      }
      lrcData = lrcLines.join('\n');
    }

    return {
      audioBuffer,
      subtitleText: explanationTextEN,
      lrcData
    };
  } catch (error: any) {
    // Handle OpenAI API errors
    if (error.status) {
      const errorMessage = error.message || 'Erro desconhecido da API OpenAI';
      throw new Error(`Erro da API OpenAI (${error.status}): ${errorMessage}`);
    }
    // Handle other errors
    const errorMessage = error.message || String(error);
    throw new Error(`Erro ao gerar áudio: ${errorMessage}`);
  }
}

/**
 * Generate exercises/questions from a screenshot image using OpenAI Vision API
 * @param imagePath - Path to the image file
 * @returns JSON object with exercises/questions
 */
export async function generateExercises(
  imagePath: string
): Promise<{ exercises: Array<{ question: string; options: string[]; correctAnswer: number; explanation: string }> }> {
  try {
    // Check if image file exists
    try {
      await fs.access(imagePath);
    } catch {
      throw new Error(`Arquivo de imagem não encontrado: ${imagePath}`);
    }

    const openai = getOpenAIClient();

    // Read image file and convert to base64
    const imageBuffer = await fs.readFile(imagePath);
    const base64Image = imageBuffer.toString('base64');
    
    const ext = path.extname(imagePath).toLowerCase();
    let mimeType = 'image/png';
    if (ext === '.jpg' || ext === '.jpeg') {
      mimeType = 'image/jpeg';
    } else if (ext === '.png') {
      mimeType = 'image/png';
    } else if (ext === '.webp') {
      mimeType = 'image/webp';
    }

    const exercisesPrompt = `Você é uma professora experiente que cria questões de exercícios educacionais. Analise esta imagem de uma página de material didático e crie questões de múltipla escolha baseadas no conteúdo apresentado.

Requisitos:
- Crie 5 questões de múltipla escolha relevantes ao conteúdo da página
- Cada questão deve ter 4 alternativas (A, B, C, D)
- As questões devem testar a compreensão do conteúdo, não apenas memorização
- Inclua uma explicação clara para cada resposta correta
- As questões devem variar em dificuldade (algumas mais fáceis, outras mais desafiadoras)
- Use linguagem clara e adequada ao nível educacional do material

Retorne APENAS um JSON válido no seguinte formato, sem markdown ou explicações adicionais:
{
  "exercises": [
    {
      "question": "Texto da pergunta aqui",
      "options": ["Alternativa A", "Alternativa B", "Alternativa C", "Alternativa D"],
      "correctAnswer": 0,
      "explanation": "Explicação detalhada da resposta correta"
    }
  ]
}

O campo "correctAnswer" deve ser um número de 0 a 3, onde 0 = primeira alternativa (A), 1 = segunda (B), 2 = terceira (C), 3 = quarta (D).`;

    // Generate exercises from image
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: 'Você é uma professora experiente que cria questões educacionais claras e bem estruturadas. Sempre retorne JSON válido.'
        },
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: exercisesPrompt
            },
            {
              type: 'image_url',
              image_url: {
                url: `data:${mimeType};base64,${base64Image}`
              }
            }
          ]
        }
      ],
      max_tokens: 3000,
      response_format: { type: 'json_object' }
    });

    const content = response.choices[0]?.message?.content;
    
    if (!content) {
      throw new Error('Não foi possível gerar os exercícios');
    }

    // Parse JSON response
    let exercisesData;
    try {
      exercisesData = JSON.parse(content);
    } catch (parseError) {
      // Try to extract JSON from markdown code blocks if present
      let cleanedContent = content.trim();
      if (cleanedContent.includes('```json')) {
        cleanedContent = cleanedContent.replace(/^```json\n?/, '').replace(/\n?```$/, '');
      } else if (cleanedContent.includes('```')) {
        cleanedContent = cleanedContent.replace(/^```\n?/, '').replace(/\n?```$/, '');
      }
      exercisesData = JSON.parse(cleanedContent);
    }

    // Validate structure
    if (!exercisesData.exercises || !Array.isArray(exercisesData.exercises)) {
      throw new Error('Formato de resposta inválido: esperado array de exercícios');
    }

    // Validate each exercise
    for (const exercise of exercisesData.exercises) {
      if (!exercise.question || !exercise.options || !Array.isArray(exercise.options) || 
          exercise.options.length !== 4 || typeof exercise.correctAnswer !== 'number' ||
          exercise.correctAnswer < 0 || exercise.correctAnswer > 3 || !exercise.explanation) {
        throw new Error('Formato de exercício inválido');
      }
    }

    return exercisesData;
  } catch (error: any) {
    // Handle OpenAI API errors
    if (error.status) {
      const errorMessage = error.message || 'Erro desconhecido da API OpenAI';
      throw new Error(`Erro da API OpenAI (${error.status}): ${errorMessage}`);
    }
    // Handle other errors
    const errorMessage = error.message || String(error);
    throw new Error(`Erro ao gerar exercícios: ${errorMessage}`);
  }
}

/**
 * Generate an image using DALL-E based on a description
 * @param description - Detailed description of the image to generate
 * @param screenshotId - ID of the screenshot (for organizing images)
 * @returns Object with imagePath and imageUrl
 */
export async function generateImageWithDALLE(
  description: string,
  screenshotId: string
): Promise<{ imagePath: string; imageUrl: string }> {
  try {
    const openai = getOpenAIClient();

    console.log(`🎨 Gerando imagem com DALL-E: ${description.substring(0, 50)}...`);

    // Generate image using DALL-E 3
    const response = await openai.images.generate({
      model: 'dall-e-3',
      prompt: description,
      n: 1,
      size: '1024x1024',
      quality: 'standard',
      response_format: 'url'
    });

    if (!response.data || !Array.isArray(response.data) || response.data.length === 0) {
      throw new Error('Nenhuma imagem retornada pela API DALL-E');
    }

    const firstImage = response.data[0];
    if (!firstImage || !('url' in firstImage)) {
      throw new Error('Formato de resposta inválido da API DALL-E');
    }

    const imageUrl = firstImage.url;
    if (!imageUrl) {
      throw new Error('Nenhuma URL de imagem retornada pela API DALL-E');
    }

    // Get screenshot to obtain pdfId and pageNumber
    const screenshot = await getScreenshotById(screenshotId);
    if (!screenshot) {
      throw new Error(`Screenshot não encontrado: ${screenshotId}`);
    }

    // Download and save the image using new hierarchical structure
    const imageId = uuidv4();
    const imageFilename = `img-${imageId}.png`;
    
    // Ensure generated images directory exists for this page
    const imagesDir = getGeneratedImagesDir(screenshot.pdfId, screenshot.page);
    await ensureDir(imagesDir);

    const imagePath = getGeneratedImagePath(screenshot.pdfId, screenshot.page, imageFilename);

    // Download image from URL (supports both HTTP and HTTPS)
    await new Promise<void>((resolve, reject) => {
      const url = new URL(imageUrl);
      const client = url.protocol === 'https:' ? https : http;
      
      client.get(imageUrl, (response) => {
        if (response.statusCode !== 200) {
          reject(new Error(`Erro ao baixar imagem: status ${response.statusCode}`));
          return;
        }

        const fileStream = require('fs').createWriteStream(imagePath);
        response.pipe(fileStream);
        
        fileStream.on('finish', () => {
          fileStream.close();
          resolve();
        });
        
        fileStream.on('error', (err: Error) => {
          require('fs').unlink(imagePath, () => {});
          reject(err);
        });
      }).on('error', reject);
    });

    const imageUrlPath = getGeneratedImageUrl(screenshot.pdfId, screenshot.page, imageFilename);
    console.log(`✅ Imagem gerada e salva: ${imagePath}`);

    return {
      imagePath,
      imageUrl: imageUrlPath
    };
  } catch (error: any) {
    console.error('Erro ao gerar imagem com DALL-E:', error);
    throw new Error(`Erro ao gerar imagem: ${error.message || 'Erro desconhecido'}`);
  }
}

/**
 * Process HTML content and replace image placeholders with generated images
 * @param htmlContent - HTML content with GENERATE_IMAGE placeholders
 * @param screenshotId - ID of the screenshot (for organizing images)
 * @returns Processed HTML with image URLs
 */
export async function processHTMLImages(
  htmlContent: string,
  screenshotId: string
): Promise<string> {
  // Find all GENERATE_IMAGE placeholders
  const imagePlaceholderRegex = /<img\s+[^>]*src=["']GENERATE_IMAGE:([^"']+)["'][^>]*>/gi;
  const matches = Array.from(htmlContent.matchAll(imagePlaceholderRegex));

  if (matches.length === 0) {
    return htmlContent; // No images to generate
  }

  console.log(`🖼️ Encontradas ${matches.length} imagem(ns) para gerar`);

  let processedHTML = htmlContent;

  // Process each placeholder
  for (const match of matches) {
    const fullMatch = match[0];
    const description = match[1];
    const altMatch = fullMatch.match(/alt=["']([^"']*)["']/i);
    const altText = altMatch ? altMatch[1] : description;

    try {
      // Generate image
      const { imageUrl } = await generateImageWithDALLE(description, screenshotId);

      // Replace placeholder with actual image URL
      const replacement = `<img src="${imageUrl}" alt="${altText}" />`;
      processedHTML = processedHTML.replace(fullMatch, replacement);

      console.log(`✅ Imagem gerada e substituída: ${description.substring(0, 30)}...`);
    } catch (error: any) {
      console.error(`❌ Erro ao gerar imagem para "${description}":`, error);
      // Replace with a placeholder image or remove the tag
      const replacement = `<img src="/placeholder-image.png" alt="${altText}" style="background: #f0f0f0; border: 1px dashed #ccc; padding: 20px; text-align: center; color: #999;" />`;
      processedHTML = processedHTML.replace(fullMatch, replacement);
    }
  }

  return processedHTML;
}
